# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v4McKXuaXeMRSW0rFmKQev30L3DR6wVm
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

filename = "/content/drive/MyDrive/age.csv"
import csv
import matplotlib.pyplot as plt
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
for row in data:
  if '우제1동' in row[0]:
    print(row[20+3])
f.close()

filename = "/content/drive/MyDrive/age.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
result=[]
loc_name = input('지역 이름 입력: ')
for row in data:
  if loc_name in row[0]:
    for i in row[3:]:
      result.append(int(i.replace(',','')))
f.close()
print(result)
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.title(f'{loc_name} 지역 구조')
plt.plot(result)
plt.show()

import matplotlib.pyplot as plt
plt.bar([0,1,2,5,6,10],[1,2,3,5,6,7])
plt.show()

import matplotlib.pyplot as plt
plt.bar(range(6),[1,2,3,5,6,7])
plt.show()

filename = "/content/drive/MyDrive/age.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
result=[]
loc_name = input('지역 이름 입력: ')
for row in data:
  if loc_name in row[0]:
    for i in row[3:]:
      result.append(int(i.replace(',','')))
f.close()
print(result)
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.title(f'{loc_name} 지역 구조')
plt.bar(range(101),result)
plt.show()

filename = "/content/drive/MyDrive/age.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
result=[]
loc_name = input('지역 이름 입력: ')
for row in data:
  if loc_name in row[0]:
    for i in row[3:]:
      result.append(int(i.replace(',','')))
f.close()
print(result)
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.title(f'{loc_name} 지역 구조')
plt.barh(range(101),result)
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
result=[]
loc_name = "부산광역시 연제구 연산제1동"
male=[]
num=[]
for row in data:
  if loc_name in row[0]:
    for i in range(0,101):
      male.append(int(row[i+3]))
      print(row[i+106])
      #num.append(int(row[i+106]))
f.close()
print(f'남성{male}')
print(f'여성{num}')
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.title(f'{loc_name} 지역 구조')
plt.barh(range(101),result)
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = input('지역 이름 입력: ')
male = []
female = []

for row in data:
  if loc_name in row[0]:
    for i in range(0,101):
      male.append(-int(row[i+3]))
      female.append(int(row[i+106]))
f.close()
print(f'남성{male}')
print(f'여성{female}')
import matplotlib.pyplot as plt
plt.ecParams['axes.unicode_minus'] = False
plt.style.use('ggplot')
plt.figure(figsize=(12,8))

plt.show()

#pie() 함수
import matplotlib.pyplot as plt
plt.pie([10,20])
plt.show()

#pie() 함수
import matplotlib.pyplot as plt
plt.pie([10,30])
plt.show()

#pie() 함수
import matplotlib.pyplot as plt
size = [2441,2312,1031,1233]
plt.axis('equal')
plt.pie(size)
plt.show()

#pie() 함수
import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

size = [2441,2312,1031,1233]

label = ['A형','B형','AB형','O형']
plt.axis('equal')
plt.pie(size,labels=label)
plt.show()

#pie() 함수
import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

size = [2441,2312,1031,1233]

label = ['A형','B형','AB형','O형']
plt.axis('equal')
plt.pie(size,labels=label,autopct='%.1f%%')
plt.legend()
plt.show()

#pie() 함수
import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

size = [2441,2312,1031,1233]

label = ['A형','B형','AB형','O형']
color = ['darkmagenta','deeppink','hotpink','pink']
plt.axis('equal')
plt.pie(size,labels=label,colors = color,autopct='%.1f%%',explode=(0,0,0.1,0))
plt.legend()
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "부산광역시 연제구 연산제1동"

sum = []
for row in data:
  if loc_name in row[0]:
    male = 0
    female = 0
    for i in range(0,101):
      male += int(row[i+3].replace(',',','))
      female += int(row[i+106].replace(',',','))
sum.append(male)
sum.append(female)
f.close()

print(sum)

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "부산광역시 연제구 연산제1동"

sum = []
for row in data:
  if loc_name in row[0]:
    male = 0
    female = 0
    for i in range(0,101):
      male += int(row[i+3].replace(',',','))
      female += int(row[i+106].replace(',',','))
sum.append(male)
sum.append(female)
f.close()

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

label = ['남성','여성']
color = ['skyblue','pink']
plt.axis('equal')
plt.pie(sum,labels=label,colors = color,autopct='%.1f%%',startangle=90,explode=(0,0.1))
plt.legend()
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "장전제1동"
male = []
female = []

for row in data:
  if loc_name in row[0]:
    for i in range(3,104):
      male.append(int(row[i].replace(',',' ')))
      female.append(int(row[i+103].replace(',',' ')))
    break
f.close()

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False

plt.plot(male,label='남성')
plt.plot(female,label='여성')
plt.legend()
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "장전제1동"
male = []
female = []

for row in data:
  if loc_name in row[0]:
    for i in range(3,104):
      male.append(int(row[i].replace(',',' '))-int(row[i+103].replace(',',' ')))
    break
f.close()

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False
plt.bar(range(101),male)
plt.show()

#산점도
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.scatter([1,2,3,4],[10,30,20,40])
plt.show()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.scatter([1,2,3,4],[10,30,20,40],s=[100,200,250,300])
plt.show()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.scatter([1,2,3,4],[10,30,20,40],s=[100,200,250,300],c=['red','blue','green','yellow'])
plt.show()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.scatter([1,2,3,4],[10,30,20,40],s=[100,200,250,300],c=['red','blue','green','yellow'])
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.scatter([1,2,3,4],[10,30,20,40],s=[100,200,250,300],c=range(4),cmap='jet')
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import random
x=[]
y=[]
size=[]
for i in range(100):
  x.append(random.randint(50,100))
  y.append(random.randint(50,100))
  size.append(random.randint(10,100))

plt.style.use('ggplot')
plt.scatter(x,y,s=size)
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import random
x=[]
y=[]
size=[]
for i in range(100):
  x.append(random.randint(50,100))
  y.append(random.randint(50,100))
  size.append(random.randint(10,100))

plt.style.use('ggplot')
plt.scatter(x,y,s=size,c=size,cmap='jet')
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import random
x=[]
y=[]
size=[]
for i in range(100):
  x.append(random.randint(50,100))
  y.append(random.randint(50,100))
  size.append(random.randint(10,100))

plt.style.use('ggplot')
plt.scatter(x,y,s=size,c=size,cmap='jet',alpha = 0.7)
plt.colorbar()
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "장전제1동"
male = []
female = []

for row in data:
  if loc_name in row[0]:
    for i in range(3,104):
      male.append(int(row[i].replace(',',' ')))
      female.append(int(row[i+103].replace(',',' ')))
    break
f.close()

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False
plt.style.use('ggplot')
plt.scatter(male,female)
plt.colorbar()
plt.show()

filename = "/content/drive/MyDrive/gender.csv"
import csv
f = open(filename, 'r',encoding='cp949')
data = csv.reader(f)
head = next(data)
loc_name = "장전제1동"
male = []
female = []

for row in data:
  if loc_name in row[0]:
    for i in range(3,104):
      male.append(int(row[i].replace(',',' ')))
      female.append(int(row[i+103].replace(',',' ')))
    break
f.close()

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
plt.rcParams['axes.unicode_minus'] = False
plt.style.use('ggplot')
plt.scatter(male,female,c=range(101),cmap='jet',alpha=0.7)
plt.colorbar()
plt.plot()
plt.show()

