# -*- coding: utf-8 -*-
"""기초2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktwlHFDWSepINXUffve6wQF9XwVHt92j

len(): 문장열 길이 구하기<br>
count(): 문자의 개수 구하기<br>
find():문자가 처음 나오는 위치 반환, 없으면 1<br>
index(): 문자열이 처음 나오는 위치 반환, 없으면 오류<br>
join(): 문자열 사이에 문자 삽입, 예:'삽입문자'join(문자열)<br>
upper():소문자를 대문자로 변환<br>
lower(): 대문자를 소문자로 변환<br>
replace(): 문자열 바꾸기, 예:replace(원본, 변환 문자)<br>
split(): 문자열 나누기 - 인수가 없으면 공백(스페이스,텝 ,엔터 등 구분타)을 기준<br>
"""

#len(): 문자열 길이
x = 'Hello Python'
print(len(x))

#count(): 문자 길이
x = 'Hello Python'
print(x.count('o'))

#find(): 문자 첫 위치 변환
x = 'Hello Python'
print(x.find('h'))

#index(): 문자열의 첫 위치 반환
x = 'Hello Python'
print(x.index('H'))

#join(): 문자열 사이 문자 삽입
x = 'Hello Python'
z='-'.join(x);
print(z)

#upper(): 소문자를 대문자로
x = 'Hello Python'
print(x.upper())

#lower(): 대문자를 소문자로
x = 'Hello Python'
print(x.lower())

#replace(): 문자열 바꾸기
x = 'Hello Python'
print(x.replace('P','$'))

#split(): 문자열 나누기
x = 'Hello Python'
print(x.split(' '))

corona ='코로나 바이러스는 감기를 일으키는 바이러스 중의 하나로 겨울철 감기를 일으키는 원인의 10~30%를 차지합니다. 코로나바이러스에 감염이되면 두통이나 목의 통증, 기침을 동반한 코감기 증상을 나타나게 합니다. 코로나바이러스를 현미경으로 보면 모양이 태양 외곽의 붉고 둥근 띠를 뜻하는 `코로나(corona)\'와 비슷하게 보여 붙혀진 이름입니다.'
print(corona.count('다'))
x = input()
print(corona.count(x))

"""- 리스트 생성 : []또는 리스트 함수 이용
- 인덱싱
 - 요소의 선택은 0부터 시작되는 인덱스로 접근
 - 리스트명[인덱스]
- 슬라이싱
 - 요소의 일부분 선택
 - 리스트명[시작인덱스:종료인덱스]
 - 종료 인덱스는 포함되지 않음
- 연산
 - +연산:리스트와 리스트 연결
 - *연산:리스트 요소 반복
- 추가
 - 리스트명.append(추가요소):마지막에 추가
 - 리스트명.insert(인덱스,추가요소):해당 인덱스에 요소 추가
- 삭제
 - 리스트명.pop():마지막 요소 삭제
 - 리스트명.pop(인덱스):해당 인덱스 요소 삭제
 - 리스트명.remove(요소값):해당 요소값 삭제, 해당 값이 없으면 오류
- 수정
 - 리스트명[인덱스] = 변경값
- 위치 반환
 - 리스트명.index(요소값)
 - 해당 요소값의 위치를 반환
 - 여러 개 요소가 존재하면 첫 번째 위치 반환하고 없으면 오류
- 요소 개수 구하기
 - 리스트명.count(요소값)
- 정렬
 - 리스트명.sort():오름차순
 - 리스트명.sort(reverse=True):내림차순
- 뒤집기
 - 리스트명.reverse():요소를 역순으로 뒤집어 줌
"""

#리스트 생성 ; [] or list()
my_list1 = []
print(type(my_list1))

my_list2 = list()
print(type(my_list2))

my_list3=[10,20,30]
print(type(my_list3))
print(my_list3)

my_list3=[10,20,30]
print(my_list3[0])
print(my_list3[1])
print(my_list3[2])

#슬라이싱 : 요소의 일부분 선택
my_list3=[10,20,30,40,50,60,70,80,90]
print(my_list3)
print(my_list3[ : : ])
print(my_list3[0:len(my_list3):1])
print(my_list3[:])
print(my_list3[-1::-1])
print(my_list3[0::2])

#리스트의 연산
a = 1+2
print(a)
my_list1=[10,20]
my_list2=[100,200]
my_list3 = my_list1+my_list2
print(my_list3)

#리스트 추가
#리스트.append(추가 요소) : 마지막에 추가
#리스트명.insert(인덱스,. 추가요소) : 해당 인덱스에 요소 추가
my_list1=['a','b','c']
my_list1.append('d')
print(my_list1)
my_list1.insert(0,'z')
print(my_list1)

my_time=[1,2,3]
my_temp=[20,20,25]
my_humi=[60,70,80]

#리스트의 삭제
#리스트명.pop() : 마지막 요소 삭제
#리스트명.pop()인덱스 : 해당 인덱스 요소 삭제
#리스트명.remove(요소값) : 해당 요소값 삭제, 해당 값이 없으면 오류
my_list1=['a','b','c']
my_list1.pop()
print(my_list1)
my_list1.pop(0)
print(my_list1)
my_list1.remove('b')
print(my_list1)